project:
  type: website
  output-dir: docs
website:
  title: "LUIS ORTIZ CEVALLOS"
  sidebar: 
    logo: Luis.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: zephyr
    css: styles.css
    code-fold: true
    include-after-body: graph_fold.html

editor: visual

